// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// averagePerEpochCpp
NumericVector averagePerEpochCpp(const NumericVector& x, int sf, int epochsize);
RcppExport SEXP _GGIR_averagePerEpochCpp(SEXP xSEXP, SEXP sfSEXP, SEXP epochsizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type sf(sfSEXP);
    Rcpp::traits::input_parameter< int >::type epochsize(epochsizeSEXP);
    rcpp_result_gen = Rcpp::wrap(averagePerEpochCpp(x, sf, epochsize));
    return rcpp_result_gen;
END_RCPP
}
// sumPerEpochCpp
NumericVector sumPerEpochCpp(const NumericVector& x, int sf, int epochsize);
RcppExport SEXP _GGIR_sumPerEpochCpp(SEXP xSEXP, SEXP sfSEXP, SEXP epochsizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type sf(sfSEXP);
    Rcpp::traits::input_parameter< int >::type epochsize(epochsizeSEXP);
    rcpp_result_gen = Rcpp::wrap(sumPerEpochCpp(x, sf, epochsize));
    return rcpp_result_gen;
END_RCPP
}
// enmoFusedCpp
List enmoFusedCpp(const NumericMatrix& data, int sf, int epochsize, bool do_enmo, bool do_en, bool do_enmoa, bool do_mad);
RcppExport SEXP _GGIR_enmoFusedCpp(SEXP dataSEXP, SEXP sfSEXP, SEXP epochsizeSEXP, SEXP do_enmoSEXP, SEXP do_enSEXP, SEXP do_enmoaSEXP, SEXP do_madSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< int >::type sf(sfSEXP);
    Rcpp::traits::input_parameter< int >::type epochsize(epochsizeSEXP);
    Rcpp::traits::input_parameter< bool >::type do_enmo(do_enmoSEXP);
    Rcpp::traits::input_parameter< bool >::type do_en(do_enSEXP);
    Rcpp::traits::input_parameter< bool >::type do_enmoa(do_enmoaSEXP);
    Rcpp::traits::input_parameter< bool >::type do_mad(do_madSEXP);
    rcpp_result_gen = Rcpp::wrap(enmoFusedCpp(data, sf, epochsize, do_enmo, do_en, do_enmoa, do_mad));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_GGIR_averagePerEpochCpp", (DL_FUNC) &_GGIR_averagePerEpochCpp, 3},
    {"_GGIR_sumPerEpochCpp", (DL_FUNC) &_GGIR_sumPerEpochCpp, 3},
    {"_GGIR_enmoFusedCpp", (DL_FUNC) &_GGIR_enmoFusedCpp, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_GGIR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
