# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

averagePerEpochCpp <- function(x, sf, epochsize) {
    .Call(`_GGIR_averagePerEpochCpp`, x, sf, epochsize)
}

sumPerEpochCpp <- function(x, sf, epochsize) {
    .Call(`_GGIR_sumPerEpochCpp`, x, sf, epochsize)
}

enmoFusedCpp <- function(x, y, z, sf, epochsize, do_enmo, do_en, do_enmoa, do_mad) {
    .Call(`_GGIR_enmoFusedCpp`, x, y, z, sf, epochsize, do_enmo, do_en, do_enmoa, do_mad)
}
